import React from 'react';
import { Placeholder, Table } from 'semantic-ui-react';

const ProductListItemPlaceHolder = () => {
  return (
    <Table celled>
      <Table.Header>
        <Table.Row>
          <Table.HeaderCell>
            <Placeholder.Paragraph>Index</Placeholder.Paragraph>
          </Table.HeaderCell>
          <Table.HeaderCell>
            <Placeholder.Paragraph>Name</Placeholder.Paragraph>
          </Table.HeaderCell>
          <Table.HeaderCell>
            <Placeholder.Paragraph>Category</Placeholder.Paragraph>
          </Table.HeaderCell>
          <Table.HeaderCell>
            <Placeholder.Paragraph>Brand</Placeholder.Paragraph>
          </Table.HeaderCell>
          <Table.HeaderCell>
            <Placeholder.Paragraph>Stock</Placeholder.Paragraph>
          </Table.HeaderCell>
          <Table.HeaderCell>
            <Placeholder.Paragraph>Action</Placeholder.Paragraph>
          </Table.HeaderCell>
        </Table.Row>
      </Table.Header>

      <Table.Body>
        <Table.Row>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
        </Table.Row>
      </Table.Body>
    </Table>
  );
};

export default ProductListItemPlaceHolder;
