import React from 'react';
import { Placeholder, Table } from 'semantic-ui-react';

const ImShipmentListItemPlaceholder = () => {
  return (
    <Table celled>
      <Table.Header>
        <Table.Row>
          <Table.HeaderCell>
            <Placeholder.Paragraph>Index</Placeholder.Paragraph>
          </Table.HeaderCell>
          <Table.HeaderCell>
            <Placeholder.Paragraph>Import ID</Placeholder.Paragraph>
          </Table.HeaderCell>
          <Table.HeaderCell>
            <Placeholder.Paragraph>Shipment ID</Placeholder.Paragraph>
          </Table.HeaderCell>
          <Table.HeaderCell>
            <Placeholder.Paragraph>Shipment Company</Placeholder.Paragraph>
          </Table.HeaderCell>
          <Table.HeaderCell>
            <Placeholder.Paragraph>Shipment Status</Placeholder.Paragraph>
          </Table.HeaderCell>
          <Table.HeaderCell>
            <Placeholder.Paragraph>Delivery Date</Placeholder.Paragraph>
          </Table.HeaderCell>
          <Table.HeaderCell>
            <Placeholder.Paragraph>Action</Placeholder.Paragraph>
          </Table.HeaderCell>
        </Table.Row>
      </Table.Header>

      <Table.Body>
        <Table.Row>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
        </Table.Row>
        <Table.Row>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
          <Table.Cell>
            <Placeholder.Paragraph>........</Placeholder.Paragraph>
          </Table.Cell>
        </Table.Row>
      </Table.Body>
    </Table>
  );
};

export default ImShipmentListItemPlaceholder;
